services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: bank
    ports: ["5432:5432"]

  mariadb:
    image: mariadb:11
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: bank
    ports: ["3306:3306"]
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Interface web
